# Generated by Django 4.1.1 on 2022-10-02 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('image', models.CharField(max_length=100)),
                ('price', models.CharField(max_length=10)),
                ('release_date', models.CharField(max_length=15)),
                ('lte_exists', models.CharField(max_length=30)),
                ('slug', models.SlugField(max_length=20)),
            ],
        ),
    ]
